# Generated by Django 4.2.5 on 2023-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metrictype",
            old_name="keras_native_loss",
            new_name="keras_native_metric",
        ),
    ]
