# Generated by Django 4.2.5 on 2023-09-25 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0002_rename_keras_native_loss_metrictype_keras_native_metric",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="networklayertype",
            old_name="keras_natiive_kayeer",
            new_name="keras_native_layer",
        ),
    ]
