# Generated by Django 4.2.5 on 2023-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0004_networkconfiguration_connections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkconfiguration",
            name="connections",
            field=models.JSONField(default=dict),
        ),
    ]
