# Generated by Django 4.2.6 on 2023-10-18 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0002_autokerastuner_autokerasnodetype_autokerasnode_and_more",
        ),
        ("neural_architecture", "0005_alter_networkconfiguration_connections"),
    ]

    operations = []
