# Generated by Django 4.2.6 on 2023-10-18 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0006_merge_20231018_1956"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autokerasnode",
            name="node_type",
        ),
        migrations.AlterUniqueTogether(
            name="autokerasnodetype",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="AutoKerasModel",
        ),
        migrations.DeleteModel(
            name="AutoKerasNode",
        ),
        migrations.DeleteModel(
            name="AutoKerasNodeType",
        ),
        migrations.DeleteModel(
            name="AutoKerasTuner",
        ),
    ]
