# Generated by Django 4.2.6 on 2023-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0008_autokerastunertype_autokerastuner_autokerasnodetype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerastunertype",
            name="module_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
