# Generated by Django 4.2.6 on 2023-10-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0010_rename_keras_type_autokerasnodetype_autokeras_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationfunctiontype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="autokerasnodetype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="autokerastunertype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="losstype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="metrictype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="networklayertype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="optimizertype",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
