# Generated by Django 4.2.6 on 2023-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0011_alter_activationfunctiontype_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autokerasmodel",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="autokerasmodel",
            name="outputs",
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="blocks",
            field=models.ManyToManyField(
                related_name="Blocks", to="neural_architecture.autokerasnode"
            ),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="connections",
            field=models.JSONField(default=dict),
        ),
    ]
