# Generated by Django 4.2.6 on 2023-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0012_remove_autokerasmodel_inputs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasnode",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
