# Generated by Django 4.2.6 on 2023-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0013_autokerasnode_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasmodel",
            name="node_to_layer_id",
            field=models.JSONField(default=dict),
        ),
    ]
