# Generated by Django 4.2.6 on 2023-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0014_autokerasmodel_node_to_layer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerasmodel",
            name="project_name",
            field=models.CharField(default="auto_model", max_length=100, unique=True),
        ),
    ]
