# Generated by Django 4.2.6 on 2023-10-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0011_alter_trainingmetric_neural_network"),
        ("neural_architecture", "0019_alter_dataset_data_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasmodel",
            name="callbacks",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="loss",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="runs.lossfunction",
            ),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="metrics",
            field=models.ManyToManyField(
                related_name="autokeras_metrics", to="runs.metric"
            ),
        ),
    ]
