# Generated by Django 4.2.6 on 2023-10-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0021_autokerasmodel_metric_weights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerasmodel",
            name="project_name",
            field=models.CharField(default="auto_model", max_length=100),
        ),
    ]
