# Generated by Django 4.2.6 on 2023-10-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0022_alter_autokerasmodel_project_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autokerasmodel",
            name="callbacks",
        ),
        migrations.CreateModel(
            name="CallbackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=100)),
                ("required_arguments", models.JSONField()),
                ("keras_native_callback", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "unique_together": {("module_name", "name")},
            },
        ),
    ]
