# Generated by Django 4.2.6 on 2023-10-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0023_remove_autokerasmodel_callbacks_callbacktype"),
        ("runs", "0012_callbackfunction"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasmodel",
            name="callbacks",
            field=models.ManyToManyField(
                related_name="autokeras_callbacks", to="runs.callbackfunction"
            ),
        ),
    ]
