# Generated by Django 4.2.6 on 2023-10-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0028_alter_dataset_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationfunctiontype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="autokerasnodetype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="autokerastunertype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="callbacktype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="losstype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="metrictype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="networklayertype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="optimizertype",
            name="required_arguments",
            field=models.JSONField(null=True),
        ),
    ]
