# Generated by Django 4.2.6 on 2023-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0029_alter_activationfunctiontype_required_arguments_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="callbacktype",
            name="registers_metrics",
            field=models.TextField(null=True),
        ),
    ]
