# Generated by Django 4.2.6 on 2023-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0030_callbacktype_registers_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasmodel",
            name="epochs",
            field=models.IntegerField(default=1000),
        ),
    ]
