# Generated by Django 4.2.7 on 2023-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0031_autokerasmodel_epochs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerasmodel",
            name="directory",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="autokerasrun",
            name="git_hash",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="callbacktype",
            name="registers_metrics",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dataset",
            name="data_dir",
            field=models.CharField(
                default="/home/goehrims/Masterarbeit/code/NASO/neural_architecture/datasets",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="localdataset",
            name="remote_source",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
