# Generated by Django 4.2.7 on 2023-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0037_remove_autokerasrun_prediction_metrics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationfunctiontype",
            name="keras_native_activation",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="callbacktype",
            name="keras_native_callback",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="losstype",
            name="keras_native_loss",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="metrictype",
            name="keras_native_metric",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="networklayertype",
            name="keras_native_layer",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="optimizertype",
            name="keras_native_optimizer",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pruningmethodtypes",
            name="native_pruning_method",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pruningpolicytypes",
            name="native_pruning_policy",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pruningscheduletypes",
            name="native_pruning_schedule",
            field=models.BooleanField(default=True),
        ),
    ]
