# Generated by Django 4.2.7 on 2023-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0038_alter_activationfunctiontype_keras_native_activation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="gpu",
            field=models.CharField(default="/gpu:0", max_length=20),
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="gpu",
            field=models.CharField(default="/gpu:0", max_length=20),
        ),
    ]
