# Generated by Django 4.2.7 on 2023-11-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0039_autokerasrun_gpu_kerasmodelrun_gpu"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasmodel",
            name="enable_quantization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="pruning_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningmethod",
            ),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="pruning_policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningpolicy",
            ),
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="pruning_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningschedule",
            ),
        ),
    ]
