# Generated by Django 4.2.7 on 2023-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0040_autokerasmodel_enable_quantization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="autokerasrun",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="rate",
            field=models.IntegerField(default=0),
        ),
    ]
