# Generated by Django 4.2.8 on 2023-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0042_autokerasrun_deleted_autokerasrun_deleted_by_cascade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="energy_measurements",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="energy_measurements",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
