# Generated by Django 4.2.8 on 2023-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0044_autokerasrun_memory_usage_kerasmodelrun_memory_usage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerasrun",
            name="memory_usage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="kerasmodelrun",
            name="memory_usage",
            field=models.FloatField(default=0),
        ),
    ]
