# Generated by Django 4.2.8 on 2024-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0045_alter_autokerasrun_memory_usage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="size_on_disk",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="size_on_disk",
            field=models.IntegerField(default=0),
        ),
    ]
