# Generated by Django 4.2.9 on 2024-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0046_autokerasrun_size_on_disk_kerasmodelrun_size_on_disk",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="compute_device",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="kerasmodelrun",
            name="compute_device",
            field=models.CharField(default="", max_length=20),
        ),
    ]
