# Generated by Django 4.2.10 on 2024-02-17 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0048_autokerasmodel_trial_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autokerasrun",
            old_name="energy_measurements",
            new_name="power_measurements",
        ),
        migrations.RenameField(
            model_name="kerasmodelrun",
            old_name="energy_measurements",
            new_name="power_measurements",
        ),
    ]
