# Generated by Django 4.2.10 on 2024-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0049_rename_energy_measurements_autokerasrun_power_measurements_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="autokerasrun",
            name="naso_app_version",
            field=models.CharField(default="1.0.0", max_length=10),
        ),
        migrations.AlterField(
            model_name="kerasmodelrun",
            name="naso_app_version",
            field=models.CharField(default="1.0.0", max_length=10),
        ),
    ]
