# Generated by Django 4.2.10 on 2024-03-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0051_remove_kerasmodelrun_dataset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterableNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_cluster", models.IntegerField(default=0)),
                (
                    "cluster_centroids_init",
                    models.CharField(
                        choices=[
                            ("linear", "Linear"),
                            ("random", "Random"),
                            ("kmeans", "Kmeans++"),
                            ("density", "Density Based"),
                        ],
                        default="linear",
                        max_length=7,
                    ),
                ),
                ("use_clustering", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="autokerasmodel",
            name="clustering_options",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neural_architecture.clusterablenetwork",
            ),
        ),
        migrations.AddField(
            model_name="networkconfiguration",
            name="clustering_options",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neural_architecture.clusterablenetwork",
            ),
        ),
    ]
