# Generated by Django 4.2.10 on 2024-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neural_architecture",
            "0052_clusterablenetwork_autokerasmodel_clustering_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="worker",
            field=models.CharField(default="", max_length=70),
            preserve_default=False,
        ),
    ]
