# Generated by Django 4.2.10 on 2024-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0053_autokerasrun_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="TensorFlowModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=100)),
                ("required_arguments", models.JSONField(null=True)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
                "unique_together": {("module_name", "name")},
            },
        ),
    ]
