# Generated by Django 4.2.13 on 2024-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0033_tensorflowmodel_load_model"),
        ("neural_architecture", "0054_tensorflowmodeltype"),
    ]

    operations = [
        migrations.AddField(
            model_name="autokerasrun",
            name="inference_metrics",
            field=models.ManyToManyField(
                related_name="autokeras_inference_metrics", to="runs.trainingmetric"
            ),
        ),
    ]
