# Generated by Django 4.2.5 on 2023-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="final_metrics",
            field=models.ManyToManyField(to="runs.trainingmetric"),
        ),
    ]
