# Generated by Django 4.2.6 on 2023-10-18 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0002_alter_fitparameters_verbose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitparameters",
            name="verbose",
        ),
    ]
