# Generated by Django 4.2.5 on 2023-09-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0003_remove_networktraining_final_metrics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="final_metrics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="runs.trainingmetric",
            ),
        ),
    ]
