# Generated by Django 4.2.5 on 2023-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0004_alter_networktraining_final_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitparameters",
            name="initial_epoch",
            field=models.IntegerField(default=0),
        ),
    ]
