# Generated by Django 4.2.5 on 2023-09-25 22:58

from django.db import migrations, models

import neural_architecture.validators


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0005_alter_fitparameters_initial_epoch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="dtype",
            field=models.CharField(
                max_length=20,
                validators=[neural_architecture.validators.validate_dtype],
            ),
        ),
    ]
