# Generated by Django 4.2.6 on 2023-10-18 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0004_networktraining_state"),
        ("runs", "0006_alter_metric_dtype"),
    ]

    operations = []
