# Generated by Django 4.2.6 on 2023-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0008_remove_networktraining_state_fitparameters_verbose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="naso_app_version",
            field=models.CharField(default="0.1.1", max_length=10),
        ),
    ]
