# Generated by Django 4.2.6 on 2023-10-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0010_alter_networktraining_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmetric",
            name="neural_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="runs.networktraining",
            ),
        ),
    ]
