# Generated by Django 4.2.6 on 2023-10-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0023_remove_autokerasmodel_callbacks_callbacktype"),
        ("runs", "0011_alter_trainingmetric_neural_network"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_arguments", models.JSONField()),
                (
                    "instance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="neural_architecture.callbacktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
