# Generated by Django 4.2.7 on 2023-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0012_callbackfunction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="git_hash",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
    ]
