# Generated by Django 4.2.7 on 2023-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0013_alter_networktraining_git_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="naso_app_version",
            field=models.CharField(default="0.1.2", max_length=10),
        ),
    ]
