# Generated by Django 4.2.7 on 2023-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0016_networktraining_prediction_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationparameters",
            name="callbacks",
            field=models.ManyToManyField(
                null=True,
                related_name="evaluation_callbacks",
                to="runs.callbackfunction",
            ),
        ),
        migrations.AlterField(
            model_name="fitparameters",
            name="callbacks",
            field=models.ManyToManyField(
                null=True,
                related_name="fitparameters_callbacks",
                to="runs.callbackfunction",
            ),
        ),
    ]
