# Generated by Django 4.2.7 on 2023-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0017_alter_evaluationparameters_callbacks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationparameters",
            name="callbacks",
            field=models.ManyToManyField(
                related_name="evaluation_callbacks", to="runs.callbackfunction"
            ),
        ),
        migrations.AlterField(
            model_name="fitparameters",
            name="callbacks",
            field=models.ManyToManyField(
                related_name="fitparameters_callbacks", to="runs.callbackfunction"
            ),
        ),
    ]
