# Generated by Django 4.2.7 on 2023-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0019_remove_networktraining_prediction_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="gpu",
            field=models.CharField(default="/gpu:0", max_length=20),
        ),
    ]
