# Generated by Django 4.2.8 on 2023-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0022_networktraining_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="energy_measurements",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
