# Generated by Django 4.2.8 on 2023-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0023_networktraining_energy_measurements"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="memory_usage",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="networktraining",
            name="naso_app_version",
            field=models.CharField(default="0.4.6", max_length=10),
        ),
    ]
