# Generated by Django 4.2.8 on 2023-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0024_networktraining_memory_usage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networktraining",
            name="memory_usage",
            field=models.FloatField(default=0),
        ),
    ]
