# Generated by Django 4.2.8 on 2024-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0025_alter_networktraining_memory_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="size_on_disk",
            field=models.IntegerField(default=0),
        ),
    ]
