# Generated by Django 4.2.10 on 2024-02-17 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0027_networktraining_compute_device"),
    ]

    operations = [
        migrations.RenameField(
            model_name="networktraining",
            old_name="energy_measurements",
            new_name="power_measurements",
        ),
    ]
