# Generated by Django 4.2.10 on 2024-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0029_alter_networktraining_naso_app_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="worker",
            field=models.CharField(default="", max_length=70),
            preserve_default=False,
        ),
    ]
