# Generated by Django 4.2.10 on 2024-05-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("neural_architecture", "0054_tensorflowmodeltype"),
        ("runs", "0031_tensorflowmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktraining",
            name="tensorflow_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="runs.tensorflowmodel",
            ),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="clustering_options",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neural_architecture.clusterablenetwork",
            ),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="enable_quantization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="model_file",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="pruning_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningmethod",
            ),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="pruning_policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningpolicy",
            ),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="pruning_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neural_architecture.pruningschedule",
            ),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="save_model",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tensorflowmodel",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networktraining",
            name="network_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="neural_architecture.networkconfiguration",
            ),
        ),
    ]
