# Generated by Django 4.2.10 on 2024-02-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("neural_architecture", "0048_autokerasmodel_trial_folder"),
        ("runs", "0027_networktraining_compute_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_file", models.CharField(default="", max_length=256)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("gpu", models.CharField(default="/gpu:0", max_length=20)),
                ("compute_device", models.CharField(default="", max_length=20)),
                (
                    "callbacks",
                    models.ManyToManyField(
                        related_name="inference_callbacks", to="runs.callbackfunction"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="neural_architecture.dataset",
                    ),
                ),
                ("metrics", models.ManyToManyField(to="runs.metric")),
                (
                    "network_training",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="runs.networktraining",
                    ),
                ),
                (
                    "prediction_metrics",
                    models.ManyToManyField(
                        related_name="inference_prediction_metrics",
                        to="runs.trainingmetric",
                    ),
                ),
            ],
        ),
    ]
