# Generated by Django 4.2.10 on 2024-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inference",
            name="batch_size",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
