# Generated by Django 4.2.10 on 2024-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0002_inference_batch_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inference",
            name="batch_size",
            field=models.IntegerField(default=1),
        ),
    ]
