# Generated by Django 4.2.10 on 2024-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0003_alter_inference_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="inference",
            name="flops",
            field=models.IntegerField(default=0),
        ),
    ]
