# Generated by Django 4.2.6 on 2023-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("python_file", models.FileField(upload_to="")),
                ("config_file", models.FileField(upload_to="")),
            ],
        ),
    ]
