# Generated by Django 4.2.6 on 2023-10-24 14:19

from django.db import migrations, models
import plugins.models.plugins


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="config_file",
            field=models.FileField(
                storage=plugins.models.plugins.OverwriteStorage(), upload_to="plugins"
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="python_file",
            field=models.FileField(
                storage=plugins.models.plugins.OverwriteStorage(), upload_to="plugins"
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="version",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name="plugin",
            unique_together={("name", "version")},
        ),
    ]
