# Generated by Django 4.2.13 on 2024-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0002_alter_plugin_config_file_alter_plugin_python_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugin",
            name="config_file",
        ),
        migrations.RemoveField(
            model_name="plugin",
            name="python_file",
        ),
        migrations.AddField(
            model_name="plugin",
            name="folder_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
