# Generated by Django 4.2.13 on 2024-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plugins",
            "0003_remove_plugin_config_file_remove_plugin_python_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="folder_name",
            field=models.CharField(max_length=200),
        ),
    ]
