# Generated by Django 4.2.13 on 2024-05-13 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celeryworker",
            name="concurrency",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="celeryworker",
            name="last_active",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 13, 19, 24, 37, 130894)
            ),
            preserve_default=False,
        ),
    ]
