TENSORFLOW_DTYPES = {
    "bool": "Boolean",
    "complex128": "128-bit complex.",
    "complex64": "'64-bit complex.",
    "double": "64-bit (double precision) floating-point.",
    "float16": "16-bit (half precision) floating-point.",
    "float32": "32-bit (single precision) floating-point.",
    "float64": "64-bit (double precision) floating-point.",
    "half": "'16':-bit (half precision) floating-point.",
    "int16": "Signed 16-bit integer.",
    "int32": "Signed 32-bit integer.",
    "int64": "Signed 64-bit integer.",
    "int8": "Signed 8-bit integer.",
    "qint16": "Signed quantized 16-bit integer.",
    "qint32": "signed quantized 32-bit integer.",
    "qint8": "Signed quantized 8-bit integer.",
    "quint16": "Unsigned quantized 16-bit integer.",
    "quint8": "Unsigned quantized 8-bit integer.",
    "resource": "Handle to a mutable, dynamically allocated resource.",
    "string": "Variable-length string, represented as byte array.",
    "uint16": "Unsigned 16-bit (word) integer.",
    "uint32": "Unsigned 32-bit (dword) integer.",
    "uint64": "Unsigned 64-bit (qword) integer.",
    "uint8": "Unsigned 8-bit (byte) integer.",
    "variant": "Data of arbitrary type (known at runtime).",
}
