"""
Django settings for naso project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from decouple import config

from .settings_base import *

ALLOWED_HOSTS = [
    "127.0.0.1",
    config("DEFAULT_HOST", default="localhost"),
    "code.mariusgoehring.de",
]
TRUSTED_ORIGINS = ["https://code.mariusgoehring.de"]
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
