
repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
        args: ["--extension=html", "--reformat"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0 # automatically updated by Commitizen
    hooks:
      - id: commitizen
